import pyautogui as bot

bot.click(204,233)
while True:
    bot.sleep(1)
    bot.hotkey('ctrl','a')
    bot.write('326')
    bot.press('tab')
    bot.press('tab')
    bot.write('ENCERRAMENTO DAS CONTAS DE RESULTADO REF AO ANO DE 2024')
    bot.press('enter')
    bot.press('enter')
    bot.sleep(0.5)

    bot.write('327')
    bot.press('tab')
    bot.press('tab')
    bot.write('ENCERRAMENTO DAS CONTAS DE RESULTADO REF AO ANO DE 2025')
    bot.press('enter')
    bot.press('enter')
    bot.sleep(0.5)

    bot.write('328')
    bot.press('tab')
    bot.press('tab')
    bot.write('ENCERRAMENTO DAS CONTAS DE RESULTADO REF AO ANO DE 2026')
    bot.press('enter')
    bot.press('enter')
    bot.sleep(0.5)

    bot.write('329')
    bot.press('tab')
    bot.press('tab')
    bot.write('ENCERRAMENTO DAS CONTAS DE RESULTADO REF AO ANO DE 2027')
    bot.press('enter')
    bot.press('enter')
    bot.sleep(0.5)

    bot.click(934,17)
    bot.sleep(0.2)
    bot.click(934,17)
    bot.sleep(0.2)
    bot.click(906,59)
    bot.sleep(0.2)
    bot.click(738,411)
    bot.sleep(1.2)
    bot.scroll(-2000)
    bot.press('end')
    bot.press('end')
    bot.sleep(0.3)
    bot.click(462,621)
    bot.press('down')
    bot.press('enter')
    bot.press('tab')
    bot.press('enter')
    bot.sleep(3)
    bot.click(917,220)
    bot.sleep(1)
    bot.click(33,508)
    bot.sleep(0.3)
    bot.click(33,508)
    bot.sleep(1)
    bot.click(48,554)
    bot.sleep(1)
    bot.click(282,59)
    bot.sleep(1)
    bot.moveTo(531,220)
    bot.sleep(0.5)
    bot.click(615,220)
    bot.sleep(2.2)
    bot.click(499,573) 
    bot.sleep(1.5)
    bot.hotkey('win', 'left')
    bot.sleep(1.5)
    bot.click(279,610)
    bot.sleep(1.5)
    bot.click(994,589)
    bot.sleep(1)
    bot.hotkey('win', 'left')
    



