import pyautogui as bot
num_inic = str(input("Num nota inicial: "))
num_final = str(input("Num nota final: "))
data = str(input("data: "))
valor = str(input("Valor: "))


bot.click(1804, 17)
bot.sleep(0.5)
bot.click(329,292)
bot.write('3317')
bot.press('enter')
bot.write('8000')
bot.press('enter')
bot.write('55')
bot.press('enter')
bot.write('NSE')
bot.press('enter')
bot.write('ISS')
bot.press('enter')
bot.press('enter')
bot.write(num_inic)
bot.press('enter')
bot.write(num_final)
bot.press('enter')
bot.write(data)
bot.press('enter')
bot.press('enter')
bot.press('enter')
bot.write(valor)

for i in range(6):
            bot.press("enter")

bot.write("0")
bot.press("enter")
bot.press("enter")
bot.write("0")
bot.press("enter")
bot.write("0")
bot.press("enter")
bot.write("0")
bot.press("enter")
bot.press("enter")
bot.write("0")
bot.press("enter")
bot.write("0")
bot.press("enter")
bot.write("0")
bot.press("enter")
bot.write("0")
bot.press("enter")
bot.press("enter")
bot.press("enter")
bot.write("0")
bot.press("enter")
bot.write("0")
bot.press("enter")
bot.press("enter")